export const eventList2 = [
  {
    EventName: "Music Festival",
    EventImage: "https://picsum.photos/1080/1920?random=1",
    EventCategory: "Music",
    LikeStatus: 1,
    starRating: 1,
  },
  {
    EventName: "Comedy Show",
    EventImage: "https://picsum.photos/1080/1920?random=2",
    EventCategory: "Comedy",
    LikeStatus: 0,
    starRating: 3,
  },
  {
    EventName: "Art Exhibit",
    EventImage: "https://picsum.photos/1080/1920?random=3",
    EventCategory: "Art",
    LikeStatus: 0,
    starRating: Math.floor(Math.random() * 5) + 1,
  },
  {
    EventName: "Food Festival",
    EventImage: "https://picsum.photos/1080/1920?random=4",
    EventCategory: "Food",
    LikeStatus: 0,
    starRating: Math.floor(Math.random() * 5) + 1,
  },
  {
    EventName: "Sports Tournament",
    EventImage: "https://picsum.photos/1080/1920?random=5",
    EventCategory: "Sports",
    LikeStatus: 1,
    starRating: 1,
  },
  {
    EventName: "Music Festival",
    EventImage: "https://picsum.photos/1080/1920?random=6",
    EventCategory: "Music",
    LikeStatus: 1,
    starRating: 1,
  },
  {
    EventName: "Comedy Show",
    EventImage: "https://picsum.photos/1080/1920?random=7",
    EventCategory: "Comedy",
    LikeStatus: 0,
    starRating: 3,
  },
  {
    EventName: "Art Exhibit",
    EventImage: "https://picsum.photos/1080/1920?random=8",
    EventCategory: "Art",
    LikeStatus: 1,
    starRating: Math.floor(Math.random() * 5) + 1,
  },
  {
    EventName: "Food Festival",
    EventImage: "https://picsum.photos/1080/1920?random=9",
    EventCategory: "Food",
    LikeStatus: 0,
    starRating: Math.floor(Math.random() * 5) + 1,
  },
  {
    EventName: "Sports Tournament",
    EventImage: "https://picsum.photos/1080/1920?random=10",
    EventCategory: "Sports",
    LikeStatus: 0,
    starRating: Math.floor(Math.random() * 5) + 1,
  },
];
